
-- Minimal app schema for MVP (Oracle SQL)
CREATE TABLE task (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL UNIQUE,
    description CLOB NULL,
    connection_id NUMBER NULL,
    http_method VARCHAR2(10) DEFAULT 'GET' NOT NULL,
    endpoint_path VARCHAR2(1000) NOT NULL,
    query_params_json CLOB CHECK (query_params_json IS JSON) NULL,
    headers_json CLOB CHECK (headers_json IS JSON) NULL,
    body_json CLOB CHECK (body_json IS JSON) NULL,
    record_path VARCHAR2(400) NULL,
    dest_table VARCHAR2(200) NOT NULL,
    batch_size NUMBER DEFAULT 500 NOT NULL,
    is_active NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP NULL
);

CREATE TABLE task_run (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    task_id NUMBER NOT NULL,
    status VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
    rows_fetched NUMBER DEFAULT 0,
    rows_inserted NUMBER DEFAULT 0,
    error_count NUMBER DEFAULT 0,
    warning_count NUMBER DEFAULT 0,
    started_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    ended_at TIMESTAMP NULL
);

CREATE INDEX ix_task_run_task_id ON task_run(task_id);
