
services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: intakegateway_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./backend:/app
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: intakegateway_worker
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./backend:/app
    command: >
      celery -A app.workers.celery_app.celery_app worker --loglevel=INFO

  scheduler:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: intakegateway_scheduler
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./backend:/app
    command: >
      python app/services/scheduler.py

  redis:
    image: redis:7-alpine
    container_name: intakegateway_redis
    ports:
      - "6379:6379"
